version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm install

  build:
    commands:
      - echo "Building React app"
      - cd frontend
      - npm run build
      - echo "Copying deployment configs"
      - cp ../appspec.yml build/
      - cp -r ../scripts build/
      - cd build
      - zip -r ../../build.zip .

artifacts:
  files:
    - build.zip
