version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm install

  build:
    commands:
      - echo "Building React app"
      - npm run build
      - echo "Preparing deploy package"
      - mkdir -p ../package
      - cp -r build/* ../package/
      - cp ../appspec.yml ../package/
      - cp -r ../scripts ../package/
      - cd ../package && zip -r ../build.zip .

artifacts:
  files:
    - build.zip