version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 
    commands:
      - echo "Installing dependencies"
      - cd frontend
      - rm -rf node_modules package-lock.json
      - npm install

  build:
    commands:
      - echo "Building React app"
      - npm run build
      - echo "Packaging deployment"
      - cp ../appspec.yml build/
      - cp -r ../scripts build/
      - cd build && zip -r ../../build.zip .

artifacts:
  files:
    - build.zip