version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm install
  build:
    commands:
      - echo "Building React app"
      - cd frontend
      - npm run build
  post_build:
    commands:
      - echo "Deploying to EC2 instance..."
      - ARTIFACT_NAME=$(date +%s)-build.zip
      - cd build && zip -r ../$ARTIFACT_NAME . && cd ..
      - aws s3 cp $ARTIFACT_NAME s3://$S3_BUCKET/$ARTIFACT_NAME
      - >
        aws ssm send-command
        --instance-ids "$INSTANCE_ID"
        --document-name "AWS-RunShellScript"
        --parameters 'commands=[
          "#!/bin/bash",
          "set -e",
          "if ! rpm -q nginx > /dev/null; then yum install -y nginx; systemctl enable nginx; fi",
          "aws s3 cp s3://$S3_BUCKET/'$ARTIFACT_NAME' /tmp/'$ARTIFACT_NAME'",
          "rm -rf /usr/share/nginx/html/*",
          "unzip /tmp/'$ARTIFACT_NAME' -d /usr/share/nginx/html",
          "systemctl restart nginx"
        ]'