apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo-app
        image: IMAGE_PLACEHOLDER 
        ports:
        - containerPort: 80